<?php

if (!isset($order_id) || $order_id == '') {
    echo "Error: Order ID is required";
    exit;
}

$employee_id = $_SESSION['employee_id'];
$model = new Model('sims');
if (!checkAdmin()) {
    $sim = $model->getByOne([ 'order_id' => $order_id, 'employee_id' => $employee_id ]);
    if ((array)$sim == []) {
        echo "Error: Order ID is not generated by you!";
        exit;
    }
}

include_once __DIR__."/../utils/http.php";

$result = checkOrder($order_id);
if ($result !== false) {
    if ($result['status'] == 'RECEIVED') {
        $url = "https://5sim.net/v1/user/ban/$order_id";
        $result = getResponse($url);
        if ($result !== false) {
            $db_res = $model->updateBy([ 'status' => $result['status'] ], [ 'order_id' => $order_id ]);
            if ($db_res !== false) {
                session_write_close();
                header("Location: /sims/" . $order_id);
            } else {
                echo "Something went wrong with database!";
            }
        } else {
            echo "Something went wrong with api!";
        }
    } else {
        echo "Something went wrong with order!";
    }
} else {
    echo "Something went wrong with api!";
}

?>
