<?php

if (!isset($order_id) || $order_id == '') {
    echo "Error: Order ID is required";
    exit;
}

$employee_id = $_SESSION['employee_id'];
$model = new Model('sims');
if (!checkAdmin()) {
    $sim = $model->getByOne([ 'order_id' => $order_id, 'employee_id' => $employee_id ]);
    if ((array)$sim == []) {
        echo "Error: Order ID is not generated by you!";
        exit;
    }
}

include_once __DIR__."/../utils/http.php";

$result = checkOrder($order_id);

$response = [ 'status' => 500, 'message' => 'Failed', 'data' => null ];

if ($result !== false) {
    $sms = end($result['sms']);
    $otp = $sms ? $sms['code'] : null;

    if ($otp) {
        $db_res = $model->updateBy([ 'status' => $result['status'], 'sms' => $result['sms'], 'otp' => $otp ], [ 'order_id' => $order_id ]);
        if ($db_res !== false) {
            session_write_close();
            $response['status'] = 200;
            $response['message'] = 'OTP Received';
            $response['data'] = $otp;
        } else {
            $response['message'] = 'Failed to update database';
        }
    } else {
        $response['status'] = 404;
        $response['message'] = 'No OTP Received';
    }
} else {
    $response['message'] = 'Error at api';
}
json_encode($response);

?>
